language: c
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq check pkg-config
before_script:
    - config/bootstrap
script: ./configure && make && make check
